#include "web_page.h"

const char WEB_CONFIG_HTML[] =
"<!DOCTYPE html><html><head><meta charset=\"utf-8\">"
"<title>PicoAdapterGB Config</title>"
"<style>"
"body{font-family:sans-serif;max-width:640px;margin:2em auto;padding:0 1em;}"
"fieldset{margin-bottom:1em;}label{display:block;margin-top:.5em;}"
"input[type=text],input[type=password],input[type=number],select{width:100%;box-sizing:border-box;}"
"button{margin-top:1em;padding:.5em 1em;}#msg{margin-top:1em;font-weight:bold;}"
"</style></head><body>"
"<h1>PicoAdapterGB - Setup</h1>"
"<form id=\"cfg\">"
"<fieldset><legend>WiFi</legend>"
"<label>SSID<input type=\"text\" id=\"wifi_ssid\"></label>"
"<label>Password<input type=\"password\" id=\"wifi_pass\"></label>"
"</fieldset>"
"<fieldset><legend>DNS</legend>"
"<label>DNS 1 (IP)<input type=\"text\" id=\"dns1\"></label>"
"<label>DNS 2 (IP)<input type=\"text\" id=\"dns2\"></label>"
"<label>DNS Port<input type=\"number\" id=\"dns_port\"></label>"
"</fieldset>"
"<fieldset><legend>Relay (P2P)</legend>"
"<label>Relay Server (ip)<input type=\"text\" id=\"relay\"></label>"
"<label>Relay Token (32 hex chars)<input type=\"text\" id=\"relay_token\"></label>"
"<label>P2P Port<input type=\"number\" id=\"p2p_port\"></label>"
"</fieldset>"
"<fieldset><legend>Adapter</legend>"
"<label>Device<select id=\"device\">"
"<option value=\"BLUE\">Blue (PDC)</option>"
"<option value=\"YELLOW\">Yellow (cdmaOne)</option>"
"<option value=\"GREEN\">Green (PHS-NTT)</option>"
"<option value=\"RED\">Red (DDI)</option>"
"</select></label>"
"<label><input type=\"checkbox\" id=\"unmetered\"> Unmetered (Pokemon Crystal)</label>"
"<label><input type=\"checkbox\" id=\"redirect_mail\"> Redirect SMTP to alt port</label>"
"</fieldset>"
"<fieldset><legend>Mobile Adapter EEPROM (.bin)</legend>"
"<label>Upload eeprom.bin<input type=\"file\" id=\"eeprom_file\" accept=\".bin\"></label>"
"<label><input type=\"checkbox\" id=\"eeprom_replace_libmobile\"> Overwrite libmobile config too (full 512 bytes)</label>"
"<button type=\"button\" id=\"eeprom_upload\">Upload eeprom.bin</button>"
"<button type=\"button\" id=\"eeprom_dump\">Download eeprom.bin</button>"
"</fieldset>"
"<button type=\"submit\">Save &amp; Reboot</button>"
"<button type=\"button\" id=\"fmt\">Format EEPROM</button>"
"</form>"
"<div id=\"msg\"></div>"
"<div id=\"ver\"></div>"
"<script>"
"async function load(){"
"console.log('[web] loading config');"
"try{"
"const r=await fetch('/api/config');"
"console.log('[web] config response status',r.status,'content-type',r.headers.get('content-type'));"
"const text=await r.text();"
"console.log('[web] config raw body',text);"
"const j=JSON.parse(text);"
"wifi_ssid.value=j.wifi_ssid;wifi_pass.value=j.wifi_pass;dns1.value=j.dns1;dns2.value=j.dns2;dns_port.value=j.dns_port;"
"relay.value=j.relay;relay_token.value=j.relay_token;p2p_port.value=j.p2p_port;"
"device.value=j.device;unmetered.checked=j.unmetered;redirect_mail.checked=j.redirect_mail;"
"ver.textContent='libmobile '+j.libmobile_version+' / '+j.firmware_version;"
"msg.textContent='Loaded current config.';"
"}catch(err){"
"console.error('[web] load config failed',err);"
"msg.textContent='Failed to load current config. Check browser console.';"
"}"
"}"
"function fields(){"
"const p=new URLSearchParams();"
"p.set('wifi_ssid',wifi_ssid.value);"
"p.set('wifi_pass',wifi_pass.value);"
"p.set('dns1',dns1.value);p.set('dns2',dns2.value);p.set('dns_port',dns_port.value);"
"p.set('relay',relay.value);p.set('relay_token',relay_token.value);p.set('p2p_port',p2p_port.value);"
"p.set('device',device.value);p.set('unmetered',unmetered.checked?'1':'0');"
"p.set('redirect_mail',redirect_mail.checked?'1':'0');"
"return p;"
"}"
"cfg.addEventListener('submit',async function(e){"
"e.preventDefault();"
"if(!confirm('Save and reboot the adapter now?'))return;"
"console.log('[web] posting config',fields().toString());"
"try{"
"const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:fields().toString()});"
"const txt=await r.text();"
"console.log('[web] config POST status',r.status,'body',txt);"
"const j=txt?JSON.parse(txt):{};"
"if(!r.ok){throw new Error(j.error||'config save failed');}"
"await fetch('/api/reboot',{method:'POST'});"
"msg.textContent='Saved. Rebooting...';"
"}catch(err){"
"console.error('[web] config save failed',err);"
"msg.textContent='Save failed. Check browser console.';"
"}"
"});"
"fmt.addEventListener('click',async function(){"
"if(!confirm('Format the EEPROM config? This resets adapter settings.'))return;"
"await fetch('/api/format',{method:'POST'});"
"msg.textContent='Formatted.';"
"load();"
"});"
"function decodeLibmobileBlock(buf){"
"const b=new Uint8Array(buf),base=0x100;"
"if(b[base]!==0x4C||b[base+1]!==0x4D)return null;"
"function fmtAddr(type,hostOff,portOff){"
"if(type===1)return b[base+hostOff]+'.'+b[base+hostOff+1]+'.'+b[base+hostOff+2]+'.'+b[base+hostOff+3];"
"if(type===2){const p=[];for(let i=0;i<16;i+=2)p.push(((b[base+hostOff+i]<<8)|b[base+hostOff+i+1]).toString(16).padStart(4,'0'));return p.join(':');}"
"return '';"
"}"
"const deviceRaw=b[base+0x05];"
"const deviceMap={8:'BLUE',9:'YELLOW',10:'GREEN',11:'RED'};"
"const dns1Type=b[base+0x06],dns2Type=b[base+0x07],relayType=b[base+0x0a];"
"const dnsPort=(dns1Type)?(b[base+0x1a]|(b[base+0x1b]<<8)):(dns2Type?(b[base+0x1c]|(b[base+0x1d]<<8)):53);"
"let relayToken='';"
"if(b[base+0x0b])for(let i=0;i<16;i++)relayToken+=b[base+0x50+i].toString(16).padStart(2,'0').toUpperCase();"
"return{"
"device:deviceMap[deviceRaw&0x7f]||'BLUE',"
"unmetered:(deviceRaw&0x80)!==0,"
"p2p_port:b[base+0x08]|(b[base+0x09]<<8),"
"redirect_mail:b[base+0x0c]!==0,"
"dns1:fmtAddr(dns1Type,0x20,0x1a),dns2:fmtAddr(dns2Type,0x30,0x1c),dns_port:dnsPort,"
"relay:fmtAddr(relayType,0x40,0x1e),relay_token:relayToken"
"};"
"}"
"eeprom_upload.addEventListener('click',async function(){"
"const file=eeprom_file.files[0];"
"if(!file){alert('Select a .bin file first.');return;}"
"const buf=await file.arrayBuffer();"
"if(buf.byteLength!==512){alert('Expected 512 bytes, got '+buf.byteLength+'.');return;}"
"const replace=eeprom_replace_libmobile.checked;"
"console.log('[web] uploading EEPROM',buf.byteLength,'replaceLibmobile',replace);"
"try{"
"const r=await fetch('/api/eeprom',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Eeprom-Replace-Libmobile':replace?'1':'0'},body:buf});"
"const text=await r.text();"
"console.log('[web] EEPROM upload status',r.status,'body',text);"
"const j=text?JSON.parse(text):{};"
"if(j.status!=='ok'){msg.textContent='Upload failed: '+(j.error||'unknown error');return;}"
"if(replace){"
"const decoded=decodeLibmobileBlock(buf);"
"if(decoded){"
"dns1.value=decoded.dns1;dns2.value=decoded.dns2;dns_port.value=decoded.dns_port;"
"relay.value=decoded.relay;relay_token.value=decoded.relay_token;p2p_port.value=decoded.p2p_port;"
"device.value=decoded.device;unmetered.checked=decoded.unmetered;redirect_mail.checked=decoded.redirect_mail;"
"}"
"}"
"msg.textContent='EEPROM loaded into memory (not saved yet). Click \"Save & Reboot\" to write it to flash.';"
"}catch(err){"
"console.error('[web] EEPROM upload failed',err);"
"msg.textContent='EEPROM upload failed. Check browser console.';"
"}"
"});"
"eeprom_dump.addEventListener('click',async function(){"
"console.log('[web] downloading EEPROM');"
"try{"
"const r=await fetch('/api/eeprom');"
"console.log('[web] EEPROM download status',r.status,'content-type',r.headers.get('content-type'));"
"if(!r.ok){alert('Download failed.');return;}"
"const blob=await r.blob();"
"const url=URL.createObjectURL(blob);"
"const a=document.createElement('a');a.href=url;a.download='eeprom.bin';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);"
"console.log('[web] EEPROM download blob size',blob.size);"
"}catch(err){"
"console.error('[web] EEPROM download failed',err);"
"alert('EEPROM download failed. Check browser console.');"
"}"
"});"
"load();"
"</script>"
"</body></html>";
